[Desktop Entry]
Name=Network Management
Name[bs]=Upravljanje mrežom
Name[cs]=Správa sítě
Name[da]=Netværkshåndtering
Name[de]=Netzwerkverwaltung
Name[fi]=Verkonhallinta
Name[fr]=Gestion de réseau
Name[hu]=Hálózatkezelés
Name[nl]=Netwerkbeheer
Name[pl]=Zarządzanie siecią
Name[pt]=Gestão de Rede
Name[pt_BR]=Gerenciamento de rede
Name[sk]=Správa siete
Name[sv]=Nätverkshantering
Name[tr]=Ağ Yönetimi
Name[ug]=تور باشقۇرۇش
Name[uk]=Керування мережею
Name[x-test]=xxNetwork Managementxx
Name[zh_CN]=网络管理

Comment=Network status and control
Comment[bs]=Alat za kontrolu i prikaz stanja mreže
Comment[cs]=Stav a ovládání sítě
Comment[da]=Status og kontrol over netværk
Comment[de]=Netzwerkstatus und -steuerung
Comment[fi]=Verkon tila ja hallinta
Comment[fr]=État et contrôle du réseau
Comment[hu]=Hálózatállapot és vezérlés
Comment[nl]=Netwerkstatus en besturing
Comment[pl]=Stan i sterowanie siecią
Comment[pt]=Estado e controlo da rede
Comment[pt_BR]=Estado e controle da rede
Comment[sk]=Správa a ovládanie siete
Comment[sv]=Nätverksstatus och kontroll
Comment[tr]=Ağ denetim ve durum izleme
Comment[uk]=Стеження за станом і керування мережею
Comment[x-test]=xxNetwork status and controlxx
Comment[zh_CN]=网络状态和控制

Type=Service
ServiceTypes=Plasma/Applet,Plasma/PopupApplet
Icon=network-defaultroute

X-Plasma-API=declarativeappletscript
X-Plasma-MainScript=ui/main.qml
X-Plasma-DefaultSize=350,450
X-Plasma-NotificationArea=true
X-Plasma-ConfigPlugins=plasma_nm_notifications

X-KDE-PluginInfo-Name=org.kde.plasma-nm
X-KDE-PluginInfo-Category=System Information
X-KDE-PluginInfo-Author=Jan Grulich, Lukáš Tinkl
X-KDE-PluginInfo-Email=jgrulich@redhat.com
X-KDE-PluginInfo-Version=@PLASMA_NM_VERSION@
X-KDE-PluginInfo-Website=
X-KDE-PluginInfo-License=GPL
X-KDE-PluginInfo-EnabledByDefault=true
X-KDE-ServiceTypes=Plasma/Applet,Plasma/PopupApplet
